FROM gcr.io/distroless/nodejs:16
COPY /dist/nanobus-linux_linux_amd64/nanobus /app/nanobus
COPY /lib/linux-amd64/libwasmer.so /usr/local/lib/libwasmer.so
ENV LD_LIBRARY_PATH /usr/local/lib:$LD_LIBRARY_PATH
WORKDIR /app
ENTRYPOINT ["/app/nanobus"]