apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgres
spec:
  type: bindings.postgres
  version: v1
  metadata:
  - name: url
    value: "user=postgres password=postgres host=localhost port=5432 dbname=nanobus sslmode=disable"
scopes:
  - customers