// Code generated by NanoBus codegen utilities. DO NOT EDIT.

// deno-lint-ignore-file no-explicit-any no-unused-vars ban-unused-ignore
import {
  Component,
  DataExpr,
  Handler,
  ResourceRef,
  Step,
  ValueExpr
} from "../nanobus.ts";

export interface TimeSchedulerV1Config {
  schedules: Schedule[];
}

export function TimeSchedulerV1(
  config: TimeSchedulerV1Config
): Component<TimeSchedulerV1Config> {
  return {
    uses: "nanobus.transport.time.scheduler/v1",
    with: config
  };
}

export interface Schedule {
  schedule: string;
  handler: Handler;
}
