// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCE:
 *     spec.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v9/vm"
	"github.com/actgardner/gogen-avro/v9/vm/types"
)

func writeArrayAvroCloudEventData(r []AvroCloudEventData, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeAvroCloudEventData(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayAvroCloudEventDataWrapper struct {
	Target *[]AvroCloudEventData
}

func (_ *ArrayAvroCloudEventDataWrapper) SetBoolean(v bool)     { panic("Unsupported operation") }
func (_ *ArrayAvroCloudEventDataWrapper) SetInt(v int32)        { panic("Unsupported operation") }
func (_ *ArrayAvroCloudEventDataWrapper) SetLong(v int64)       { panic("Unsupported operation") }
func (_ *ArrayAvroCloudEventDataWrapper) SetFloat(v float32)    { panic("Unsupported operation") }
func (_ *ArrayAvroCloudEventDataWrapper) SetDouble(v float64)   { panic("Unsupported operation") }
func (_ *ArrayAvroCloudEventDataWrapper) SetBytes(v []byte)     { panic("Unsupported operation") }
func (_ *ArrayAvroCloudEventDataWrapper) SetString(v string)    { panic("Unsupported operation") }
func (_ *ArrayAvroCloudEventDataWrapper) SetUnionElem(v int64)  { panic("Unsupported operation") }
func (_ *ArrayAvroCloudEventDataWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ *ArrayAvroCloudEventDataWrapper) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *ArrayAvroCloudEventDataWrapper) Finalize()        {}
func (_ *ArrayAvroCloudEventDataWrapper) SetDefault(i int) { panic("Unsupported operation") }
func (r *ArrayAvroCloudEventDataWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r *ArrayAvroCloudEventDataWrapper) AppendArray() types.Field {
	var v AvroCloudEventData
	v = NewAvroCloudEventData()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
