// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCE:
 *     spec.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v9/compiler"
	"github.com/actgardner/gogen-avro/v9/vm"
	"github.com/actgardner/gogen-avro/v9/vm/types"
)

var _ = fmt.Printf

// Representation of a JSON Value
type AvroCloudEventData struct {
	Value map[string]*UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString `json:"value"`
}

const AvroCloudEventDataAvroCRC64Fingerprint = "$6\x84\xc8i3]\\"

func NewAvroCloudEventData() AvroCloudEventData {
	r := AvroCloudEventData{}
	r.Value = make(map[string]*UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString)

	return r
}

func DeserializeAvroCloudEventData(r io.Reader) (AvroCloudEventData, error) {
	t := NewAvroCloudEventData()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeAvroCloudEventDataFromSchema(r io.Reader, schema string) (AvroCloudEventData, error) {
	t := NewAvroCloudEventData()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeAvroCloudEventData(r AvroCloudEventData, w io.Writer) error {
	var err error
	err = writeMapUnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString(r.Value, w)
	if err != nil {
		return err
	}
	return err
}

func (r AvroCloudEventData) Serialize(w io.Writer) error {
	return writeAvroCloudEventData(r, w)
}

func (r AvroCloudEventData) Schema() string {
	return "{\"doc\":\"Representation of a JSON Value\",\"fields\":[{\"name\":\"value\",\"type\":{\"type\":\"map\",\"values\":[\"null\",\"boolean\",{\"type\":\"map\",\"values\":\"io.cloudevents.AvroCloudEventData\"},{\"items\":\"io.cloudevents.AvroCloudEventData\",\"type\":\"array\"},\"double\",\"string\"]}}],\"name\":\"io.cloudevents.AvroCloudEventData\",\"type\":\"record\"}"
}

func (r AvroCloudEventData) SchemaName() string {
	return "io.cloudevents.AvroCloudEventData"
}

func (_ AvroCloudEventData) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ AvroCloudEventData) SetInt(v int32)       { panic("Unsupported operation") }
func (_ AvroCloudEventData) SetLong(v int64)      { panic("Unsupported operation") }
func (_ AvroCloudEventData) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ AvroCloudEventData) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ AvroCloudEventData) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ AvroCloudEventData) SetString(v string)   { panic("Unsupported operation") }
func (_ AvroCloudEventData) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *AvroCloudEventData) Get(i int) types.Field {
	switch i {
	case 0:
		r.Value = make(map[string]*UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString)

		return &MapUnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringWrapper{Target: &r.Value}
	}
	panic("Unknown field index")
}

func (r *AvroCloudEventData) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *AvroCloudEventData) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ AvroCloudEventData) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ AvroCloudEventData) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ AvroCloudEventData) Finalize()                        {}

func (_ AvroCloudEventData) AvroCRC64Fingerprint() []byte {
	return []byte(AvroCloudEventDataAvroCRC64Fingerprint)
}

func (r AvroCloudEventData) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["value"], err = json.Marshal(r.Value)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *AvroCloudEventData) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["value"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Value); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for value")
	}
	return nil
}
