// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCE:
 *     spec.avsc
 */
package avro

import (
	"github.com/actgardner/gogen-avro/v9/vm"
	"github.com/actgardner/gogen-avro/v9/vm/types"
	"io"
)

func writeMapAvroCloudEventData(r map[string]AvroCloudEventData, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for k, e := range r {
		err = vm.WriteString(k, w)
		if err != nil {
			return err
		}
		err = writeAvroCloudEventData(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type MapAvroCloudEventDataWrapper struct {
	Target *map[string]AvroCloudEventData
	keys   []string
	values []AvroCloudEventData
}

func (_ *MapAvroCloudEventDataWrapper) SetBoolean(v bool)     { panic("Unsupported operation") }
func (_ *MapAvroCloudEventDataWrapper) SetInt(v int32)        { panic("Unsupported operation") }
func (_ *MapAvroCloudEventDataWrapper) SetLong(v int64)       { panic("Unsupported operation") }
func (_ *MapAvroCloudEventDataWrapper) SetFloat(v float32)    { panic("Unsupported operation") }
func (_ *MapAvroCloudEventDataWrapper) SetDouble(v float64)   { panic("Unsupported operation") }
func (_ *MapAvroCloudEventDataWrapper) SetBytes(v []byte)     { panic("Unsupported operation") }
func (_ *MapAvroCloudEventDataWrapper) SetString(v string)    { panic("Unsupported operation") }
func (_ *MapAvroCloudEventDataWrapper) SetUnionElem(v int64)  { panic("Unsupported operation") }
func (_ *MapAvroCloudEventDataWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ *MapAvroCloudEventDataWrapper) SetDefault(i int)      { panic("Unsupported operation") }

func (r *MapAvroCloudEventDataWrapper) NullField(_ int) {
	panic("Unsupported operation")
}

func (r *MapAvroCloudEventDataWrapper) Finalize() {
	for i := range r.keys {
		(*r.Target)[r.keys[i]] = r.values[i]
	}
}

func (r *MapAvroCloudEventDataWrapper) AppendMap(key string) types.Field {
	r.keys = append(r.keys, key)
	var v AvroCloudEventData
	v = NewAvroCloudEventData()

	r.values = append(r.values, v)
	return &types.Record{Target: &r.values[len(r.values)-1]}
}

func (_ *MapAvroCloudEventDataWrapper) AppendArray() types.Field { panic("Unsupported operation") }
