// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCE:
 *     spec.avsc
 */
package avro

import (
	"github.com/actgardner/gogen-avro/v9/vm"
	"github.com/actgardner/gogen-avro/v9/vm/types"
	"io"
)

func writeMapUnionNullBoolAvroCloudEventDataDoubleString(r map[string]*UnionNullBoolAvroCloudEventDataDoubleString, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for k, e := range r {
		err = vm.WriteString(k, w)
		if err != nil {
			return err
		}
		err = writeUnionNullBoolAvroCloudEventDataDoubleString(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type MapUnionNullBoolAvroCloudEventDataDoubleStringWrapper struct {
	Target *map[string]*UnionNullBoolAvroCloudEventDataDoubleString
	keys   []string
	values []*UnionNullBoolAvroCloudEventDataDoubleString
}

func (_ *MapUnionNullBoolAvroCloudEventDataDoubleStringWrapper) SetBoolean(v bool) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolAvroCloudEventDataDoubleStringWrapper) SetInt(v int32) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolAvroCloudEventDataDoubleStringWrapper) SetLong(v int64) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolAvroCloudEventDataDoubleStringWrapper) SetFloat(v float32) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolAvroCloudEventDataDoubleStringWrapper) SetDouble(v float64) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolAvroCloudEventDataDoubleStringWrapper) SetBytes(v []byte) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolAvroCloudEventDataDoubleStringWrapper) SetString(v string) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolAvroCloudEventDataDoubleStringWrapper) SetUnionElem(v int64) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolAvroCloudEventDataDoubleStringWrapper) Get(i int) types.Field {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolAvroCloudEventDataDoubleStringWrapper) SetDefault(i int) {
	panic("Unsupported operation")
}

func (r *MapUnionNullBoolAvroCloudEventDataDoubleStringWrapper) NullField(_ int) {
	r.values[len(r.values)-1] = nil
}

func (r *MapUnionNullBoolAvroCloudEventDataDoubleStringWrapper) Finalize() {
	for i := range r.keys {
		(*r.Target)[r.keys[i]] = r.values[i]
	}
}

func (r *MapUnionNullBoolAvroCloudEventDataDoubleStringWrapper) AppendMap(key string) types.Field {
	r.keys = append(r.keys, key)
	var v *UnionNullBoolAvroCloudEventDataDoubleString
	v = NewUnionNullBoolAvroCloudEventDataDoubleString()

	r.values = append(r.values, v)
	return r.values[len(r.values)-1]
}

func (_ *MapUnionNullBoolAvroCloudEventDataDoubleStringWrapper) AppendArray() types.Field {
	panic("Unsupported operation")
}
