// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCE:
 *     spec.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v9/compiler"
	"github.com/actgardner/gogen-avro/v9/vm"
	"github.com/actgardner/gogen-avro/v9/vm/types"
)

type UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnum int

const (
	UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumBytes UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnum = 0

	UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumBool UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnum = 2

	UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumMapUnionNullBoolAvroCloudEventDataDoubleString UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnum = 3

	UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumArrayAvroCloudEventData UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnum = 4

	UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumDouble UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnum = 5

	UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumString UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnum = 6
)

type UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString struct {
	Bytes                                          Bytes
	Null                                           *types.NullVal
	Bool                                           bool
	MapUnionNullBoolAvroCloudEventDataDoubleString map[string]*UnionNullBoolAvroCloudEventDataDoubleString
	ArrayAvroCloudEventData                        []AvroCloudEventData
	Double                                         float64
	String                                         string
	UnionType                                      UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnum
}

func writeUnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString(r *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(1, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumBytes:
		return vm.WriteBytes(r.Bytes, w)
	case UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumBool:
		return vm.WriteBool(r.Bool, w)
	case UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumMapUnionNullBoolAvroCloudEventDataDoubleString:
		return writeMapUnionNullBoolAvroCloudEventDataDoubleString(r.MapUnionNullBoolAvroCloudEventDataDoubleString, w)
	case UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumArrayAvroCloudEventData:
		return writeArrayAvroCloudEventData(r.ArrayAvroCloudEventData, w)
	case UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumDouble:
		return vm.WriteDouble(r.Double, w)
	case UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumString:
		return vm.WriteString(r.String, w)
	}
	return fmt.Errorf("invalid value for *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString")
}

func NewUnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString() *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString {
	return &UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString{}
}

func (r *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString) Serialize(w io.Writer) error {
	return writeUnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString(r, w)
}

func DeserializeUnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString(r io.Reader) (*UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString, error) {
	t := NewUnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringFromSchema(r io.Reader, schema string) (*UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString, error) {
	t := NewUnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString) Schema() string {
	return "[\"bytes\",\"null\",\"boolean\",{\"type\":\"map\",\"values\":[\"null\",\"boolean\",{\"doc\":\"Representation of a JSON Value\",\"fields\":[{\"name\":\"value\",\"type\":{\"type\":\"map\",\"values\":[\"null\",\"boolean\",{\"type\":\"map\",\"values\":\"io.cloudevents.AvroCloudEventData\"},{\"items\":\"io.cloudevents.AvroCloudEventData\",\"type\":\"array\"},\"double\",\"string\"]}}],\"name\":\"AvroCloudEventData\",\"type\":\"record\"},\"double\",\"string\"]},{\"items\":\"io.cloudevents.AvroCloudEventData\",\"type\":\"array\"},\"double\",\"string\"]"
}

func (_ *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString) SetBoolean(v bool) {
	panic("Unsupported operation")
}
func (_ *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString) SetInt(v int32) {
	panic("Unsupported operation")
}
func (_ *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString) SetFloat(v float32) {
	panic("Unsupported operation")
}
func (_ *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString) SetDouble(v float64) {
	panic("Unsupported operation")
}
func (_ *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString) SetBytes(v []byte) {
	panic("Unsupported operation")
}
func (_ *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString) SetString(v string) {
	panic("Unsupported operation")
}

func (r *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString) SetLong(v int64) {

	r.UnionType = (UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnum)(v)
}

func (r *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString) Get(i int) types.Field {

	switch i {
	case 0:
		return &BytesWrapper{Target: (&r.Bytes)}
	case 1:
		return r.Null
	case 2:
		return &types.Boolean{Target: (&r.Bool)}
	case 3:
		r.MapUnionNullBoolAvroCloudEventDataDoubleString = make(map[string]*UnionNullBoolAvroCloudEventDataDoubleString)
		return &MapUnionNullBoolAvroCloudEventDataDoubleStringWrapper{Target: (&r.MapUnionNullBoolAvroCloudEventDataDoubleString)}
	case 4:
		r.ArrayAvroCloudEventData = make([]AvroCloudEventData, 0)
		return &ArrayAvroCloudEventDataWrapper{Target: (&r.ArrayAvroCloudEventData)}
	case 5:
		return &types.Double{Target: (&r.Double)}
	case 6:
		return &types.String{Target: (&r.String)}
	}
	panic("Unknown field index")
}
func (_ *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString) NullField(i int) {
	panic("Unsupported operation")
}
func (_ *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString) SetDefault(i int) {
	panic("Unsupported operation")
}
func (_ *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString) AppendArray() types.Field {
	panic("Unsupported operation")
}
func (_ *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString) Finalize() {
}

func (r *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumBytes:
		return json.Marshal(map[string]interface{}{"bytes": r.Bytes})
	case UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumBool:
		return json.Marshal(map[string]interface{}{"boolean": r.Bool})
	case UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumMapUnionNullBoolAvroCloudEventDataDoubleString:
		return json.Marshal(map[string]interface{}{"map": r.MapUnionNullBoolAvroCloudEventDataDoubleString})
	case UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumArrayAvroCloudEventData:
		return json.Marshal(map[string]interface{}{"array": r.ArrayAvroCloudEventData})
	case UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumDouble:
		return json.Marshal(map[string]interface{}{"double": r.Double})
	case UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleStringTypeEnumString:
		return json.Marshal(map[string]interface{}{"string": r.String})
	}
	return nil, fmt.Errorf("invalid value for *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString")
}

func (r *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["bytes"]; ok {
		r.UnionType = 0
		return json.Unmarshal([]byte(value), &r.Bytes)
	}
	if value, ok := fields["boolean"]; ok {
		r.UnionType = 2
		return json.Unmarshal([]byte(value), &r.Bool)
	}
	if value, ok := fields["map"]; ok {
		r.UnionType = 3
		return json.Unmarshal([]byte(value), &r.MapUnionNullBoolAvroCloudEventDataDoubleString)
	}
	if value, ok := fields["array"]; ok {
		r.UnionType = 4
		return json.Unmarshal([]byte(value), &r.ArrayAvroCloudEventData)
	}
	if value, ok := fields["double"]; ok {
		r.UnionType = 5
		return json.Unmarshal([]byte(value), &r.Double)
	}
	if value, ok := fields["string"]; ok {
		r.UnionType = 6
		return json.Unmarshal([]byte(value), &r.String)
	}
	return fmt.Errorf("invalid value for *UnionBytesNullBoolMapUnionNullBoolAvroCloudEventDataDoubleStringArrayAvroCloudEventDataDoubleString")
}
