// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCE:
 *     spec.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v9/compiler"
	"github.com/actgardner/gogen-avro/v9/vm"
	"github.com/actgardner/gogen-avro/v9/vm/types"
)

type UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnum int

const (
	UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnumBool UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnum = 1

	UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnumMapAvroCloudEventData UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnum = 2

	UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnumArrayAvroCloudEventData UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnum = 3

	UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnumDouble UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnum = 4

	UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnumString UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnum = 5
)

type UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString struct {
	Null                    *types.NullVal
	Bool                    bool
	MapAvroCloudEventData   map[string]AvroCloudEventData
	ArrayAvroCloudEventData []AvroCloudEventData
	Double                  float64
	String                  string
	UnionType               UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnum
}

func writeUnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString(r *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnumBool:
		return vm.WriteBool(r.Bool, w)
	case UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnumMapAvroCloudEventData:
		return writeMapAvroCloudEventData(r.MapAvroCloudEventData, w)
	case UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnumArrayAvroCloudEventData:
		return writeArrayAvroCloudEventData(r.ArrayAvroCloudEventData, w)
	case UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnumDouble:
		return vm.WriteDouble(r.Double, w)
	case UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnumString:
		return vm.WriteString(r.String, w)
	}
	return fmt.Errorf("invalid value for *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString")
}

func NewUnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString() *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString {
	return &UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString{}
}

func (r *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString) Serialize(w io.Writer) error {
	return writeUnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString(r, w)
}

func DeserializeUnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString(r io.Reader) (*UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString, error) {
	t := NewUnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringFromSchema(r io.Reader, schema string) (*UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString, error) {
	t := NewUnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString) Schema() string {
	return "[\"null\",\"boolean\",{\"type\":\"map\",\"values\":{\"doc\":\"Representation of a JSON Value\",\"fields\":[{\"name\":\"value\",\"type\":{\"type\":\"map\",\"values\":[\"null\",\"boolean\",{\"type\":\"map\",\"values\":\"io.cloudevents.AvroCloudEventData\"},{\"items\":\"io.cloudevents.AvroCloudEventData\",\"type\":\"array\"},\"double\",\"string\"]}}],\"name\":\"AvroCloudEventData\",\"type\":\"record\"}},{\"items\":\"io.cloudevents.AvroCloudEventData\",\"type\":\"array\"},\"double\",\"string\"]"
}

func (_ *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString) SetBoolean(v bool) {
	panic("Unsupported operation")
}
func (_ *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString) SetInt(v int32) {
	panic("Unsupported operation")
}
func (_ *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString) SetFloat(v float32) {
	panic("Unsupported operation")
}
func (_ *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString) SetDouble(v float64) {
	panic("Unsupported operation")
}
func (_ *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString) SetBytes(v []byte) {
	panic("Unsupported operation")
}
func (_ *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString) SetString(v string) {
	panic("Unsupported operation")
}

func (r *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString) SetLong(v int64) {

	r.UnionType = (UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnum)(v)
}

func (r *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		return &types.Boolean{Target: (&r.Bool)}
	case 2:
		r.MapAvroCloudEventData = make(map[string]AvroCloudEventData)
		return &MapAvroCloudEventDataWrapper{Target: (&r.MapAvroCloudEventData)}
	case 3:
		r.ArrayAvroCloudEventData = make([]AvroCloudEventData, 0)
		return &ArrayAvroCloudEventDataWrapper{Target: (&r.ArrayAvroCloudEventData)}
	case 4:
		return &types.Double{Target: (&r.Double)}
	case 5:
		return &types.String{Target: (&r.String)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString) NullField(i int) {
	panic("Unsupported operation")
}
func (_ *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString) SetDefault(i int) {
	panic("Unsupported operation")
}
func (_ *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString) AppendArray() types.Field {
	panic("Unsupported operation")
}
func (_ *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString) Finalize() {}

func (r *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnumBool:
		return json.Marshal(map[string]interface{}{"boolean": r.Bool})
	case UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnumMapAvroCloudEventData:
		return json.Marshal(map[string]interface{}{"map": r.MapAvroCloudEventData})
	case UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnumArrayAvroCloudEventData:
		return json.Marshal(map[string]interface{}{"array": r.ArrayAvroCloudEventData})
	case UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnumDouble:
		return json.Marshal(map[string]interface{}{"double": r.Double})
	case UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleStringTypeEnumString:
		return json.Marshal(map[string]interface{}{"string": r.String})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString")
}

func (r *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["boolean"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.Bool)
	}
	if value, ok := fields["map"]; ok {
		r.UnionType = 2
		return json.Unmarshal([]byte(value), &r.MapAvroCloudEventData)
	}
	if value, ok := fields["array"]; ok {
		r.UnionType = 3
		return json.Unmarshal([]byte(value), &r.ArrayAvroCloudEventData)
	}
	if value, ok := fields["double"]; ok {
		r.UnionType = 4
		return json.Unmarshal([]byte(value), &r.Double)
	}
	if value, ok := fields["string"]; ok {
		r.UnionType = 5
		return json.Unmarshal([]byte(value), &r.String)
	}
	return fmt.Errorf("invalid value for *UnionNullBoolMapAvroCloudEventDataArrayAvroCloudEventDataDoubleString")
}
