/*
Copyright 2022 The NanoBus Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by @nanobus/codegen. DO NOT EDIT.

package welcome

import (
	"context"
)

type ns struct{}

func (n *ns) Namespace() string {
	return "welcome.v1"
}

func (n *ns) Version() string {
	return "0.1.0"
}

type Inbound interface {
	GreetCustomer(ctx context.Context, customer *Customer) error
}

type Outbound interface {
	SendEmail(ctx context.Context, email string, message string) error
}

type Customer struct {
	ns
	FirstName string `json:"firstName" msgpack:"firstName"`
	LastName  string `json:"lastName" msgpack:"lastName"`
	Email     string `json:"email" msgpack:"email"`
}

func (c *Customer) Type() string {
	return "Customer"
}
